version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

    # Ignore all dependency manifests in the `playground` directory.
    exclude-paths:
      - playground/**
