shellEmulator: true
trustPolicy: no-downgrade

packages:
  - extensions/*
  - packages/*

catalogs:
  dev:
    '@types/node': ^25.6.0
    '@types/path-browserify': ^1.0.3
    '@types/semver': ^7.7.1
    '@typescript/native-preview': 7.0.0-dev.20260422.1
    '@vida0905/eslint-config': ^2.12.0
    eslint: ^10.2.1
    husky: ^9.1.7
    nano-staged: ^1.0.2
    tsdown: ^0.21.10
    vite: ^8.0.10
    vscode-ext-gen: ^1.6.0
  inline:
    fast-npm-meta: ^1.5.0
    jsonc-parser: ^3.3.1
    ocache: ^0.1.4
    ofetch: ^2.0.0-alpha.3
    path-browserify: ^1.0.1
    reactive-vscode: ^1.0.1
    semver: ^7.7.4
    vscode-find-up: ^0.1.1
    vscode-languageserver-textdocument: ^1.0.12
    yaml: ^2.8.3
  lsp:
    '@volar/language-server': ^2.4.28
    '@volar/language-service': ^2.4.28
    '@volar/vscode': ^2.4.28
    vscode-uri: ^3.1.0
  test:
    jest-mock-vscode: ^4.12.0
    module-replacements: ^2.11.0
    msw: ^2.13.5
    vite-tsconfig-paths: ^6.1.1
    vitest: ^4.1.5
