shellEmulator: true
trustPolicy: no-downgrade

catalogs:
  dev:
    '@types/node': ^25.3.2
    '@types/semver': ^7.7.1
    '@typescript/native-preview': 7.0.0-dev.20260309.1
    '@vida0905/eslint-config': ^2.10.1
    eslint: ^10.0.2
    husky: ^9.1.7
    nano-staged: ^0.9.0
    tsdown: ^0.21.0
    vscode-ext-gen: ^1.6.0
  inline:
    fast-npm-meta: ^1.3.0
    jsonc-parser: ^3.3.1
    ocache: ^0.1.2
    ofetch: ^2.0.0-alpha.3
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    reactive-vscode: ^1.0.0-beta.2
    semver: ^7.7.4
    vscode-find-up: ^0.1.1
    yaml: ^2.8.2
  test:
    jest-mock-vscode: ^4.11.0
    module-replacements: ^2.11.0
    msw: ^2.12.10
    vite-tsconfig-paths: ^6.1.1
    vitest: ^4.0.18
