shellEmulator: true
trustPolicy: no-downgrade

catalogs:
  dev:
    '@types/node': ^25.3.0
    '@types/semver': ^7.7.1
    '@vida0905/eslint-config': ^2.10.1
    eslint: ^10.0.1
    husky: ^9.1.7
    nano-staged: ^0.9.0
    tsdown: ^0.20.3
    typescript: ^5.9.3
    vscode-ext-gen: ^1.6.0
  inline:
    fast-npm-meta: ^1.2.1
    jsonc-parser: ^3.3.1
    module-replacements: ^2.11.0
    ofetch: ^2.0.0-alpha.3
    perfect-debounce: ^2.1.0
    reactive-vscode: ^1.0.0-beta.2
    semver: ^7.7.4
    yaml: ^2.8.2
  test:
    jest-mock-vscode: ^4.11.0
    vite-tsconfig-paths: ^6.1.1
    vitest: ^4.0.18
