id = "npmx-language-server"
name = "Npmx Language Server"
description = "Enhance your npm package workflow in Zed"
version = "0.9.3"
schema_version = 1
authors = [
  "npmx-dev",
  "Xat <i@xat.sh>",
  "Vida Xie <vida_2020@163.com>"
]
repository = "https://github.com/npmx-dev/vscode-npmx/tree/main/extensions/zed"

[language_servers.npmx-language-server]
name = "Npmx Language Server"
languages = [
  "JSON",
  "YAML",
  "JavaScript",
  "JSX",
  "TypeScript",
  "TSX",
  "HTML",
  "Vue",
  "Astro",
  "Svelte"
]

[language_servers.npmx-language-server.language_ids]
JSON = "json"
YAML = "yaml"
JavaScript = "javascript"
JSX = "javascriptreact"
TypeScript = "typescript"
TSX = "typescriptreact"
HTML = "html"
Vue = "vue"
Astro = "astro"
Svelte = "svelte"
