name: autofix.ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autofix:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
        with:
          no-frozen-lockfile: true

      - name: Fix
        run: pnpm run lint:fix

      - name: Commit
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
