name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autofix:
    uses: sxzz/workflows/.github/workflows/autofix.yml@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
    permissions:
      contents: read
