name: Publish Extension

on:
  push:
    tags:
      - v*

jobs:
  publish-extension:
    permissions:
      id-token: write
      contents: write
      actions: write

    runs-on: ubuntu-slim
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
        with:
          fetch-all: true

      - name: Build
        run: pnpm build

      - name: Generate .vsix file
        working-directory: extensions/vscode
        run: pnpm package

      - name: Publish Extension
        working-directory: extensions/vscode
        run: npx vsxpub --no-dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{secrets.VSCE_PAT}}
          OVSX_PAT: ${{secrets.OVSX_PAT}}

      - name: Generate Github Changelog
        run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
