name: Publish Extensions

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  publish-extension:
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@dd67f194be6388e12ee61ad0cd3b81cf74bfd294
        with:
          fetch-all: true

      - name: Create tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(jq -r '.version' package.json)
          gh api "repos/$GITHUB_REPOSITORY/git/refs" \
            -f ref="refs/tags/v$VERSION" \
            -f sha="${{ github.event.pull_request.merge_commit_sha }}"

      - name: Generate Github Changelog
        run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Publish npm packages to registry
        run: pnpm -r --filter './packages/*' publish --access public --no-git-checks --provenance

      - name: Generate .vsix file
        working-directory: extensions/vscode
        run: pnpm package

      - name: Publish VSCode Extension
        working-directory: extensions/vscode
        run: npx vsxpub --no-dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      # - name: Publish Zed Extension
      #   uses: huacnlee/zed-extension-action@v2
      #   with:
      #     extension-name: npmx
      #     push-to: npmx.dev/npmx
      #   env:
      #     # the personal access token should have "repo" & "workflow" scopes
      #     COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
