name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm run typecheck

      - name: Upload LSP packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          retention-days: 3
          name: lsp-packages
          path: packages/*/dist

  test:
    needs:
      - lint

    strategy:
      matrix:
        os: [ubuntu-slim, windows-latest, macos-latest]
        node-version: [22, lts/*]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    permissions: {}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download LSP packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: lsp-packages
          path: packages

      - name: Unit Test
        run: pnpm run test
