name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm run typecheck

  test:
    strategy:
      matrix:
        os: [ubuntu-slim, windows-latest, macos-latest]
        node-version: [22, lts/*]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    permissions: {}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: pnpm build

      - name: Unit Test
        run: pnpm run test
